### ISSUE TITLE
incorrect query results

### ISSUE THREAD

**Issue by nleguillarme** [globalbioticinteractions/globalbioticinteractions#1002]
Hi @jhpoelen 

I am trying to query globi for trophic interactions of Astigmata using the following query:
`https://api.globalbioticinteractions.org/taxon/Astigmata/eats?type=csv`

Here are the two first records I get:

  | source_taxon_name | interaction_type | target_taxon_name
-- | -- | -- | --
0 | Trichoecius | parasiteOf | Microtus pennsylvanicus
1 | Trichobius uniformis | ectoparasiteOf | Sturnira lilium

*Trichobius uniformis* is a fly (Diptera), not a mite (Astigmata), and the interaction type does not match either.

Am I doing something wrong here?

**Comment by jhpoelen** [comment]
@nleguillarme thanks for sharing your notes. 

re: interaction types - In my mind, a parasitic interaction is a kind of trophic interactions, because the parasite eats part of their host. Please let me know if you think we should reconsider this inference. Perhaps a "derives nutrients from" would be a more applicable generalization of a parasitic interactions to describe the relationship between the parasite and their host? 

re: Trichobius uniformis being included as a mite. . . looking into it.

**Comment by jhpoelen** [comment]
A quick search on _Trichobius uniformis	_ via https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=Trichobius%20uniformis told me that the GloBI Taxon Graph connects 

Trichobius uniformis -> Trichobius -> IRMNG Trichobius Canestrini, 1896  https://www.irmng.org/aphia.php?p=taxdetails&id=1298129 

And, according to IRMNG Trichobius appears to be an uncertain mite genus. 

![image](https://github.com/user-attachments/assets/1fed3cda-cab8-4713-ace3-7ce23bd5ca1d)

**Comment by jhpoelen** [comment]
If you'd like to be more specific in what you are looking for, you can specify the taxon id provided by some taxonomic resource.

For instance, the Catalogue of Life issued "4CP" as a the taxonomic identifier for the suborder Astigmata https://www.catalogueoflife.org/data/taxon/4CP . 

So, rather than searching by some string (i.e., `Astigmata`), you might want to consider searching by a taxonomic identifier (e.g., `COL:4CP`).

Now, instead of 

```bash
curl "https://api.globalbioticinteractions.org/taxon/Astigmata/eats?type=csv"\
 | head -3\
 | mlr --icsv --omd cat
```

| source_taxon_name | interaction_type | target_taxon_name |
| --- | --- | --- |
| Trichoecius | parasiteOf | Microtus pennsylvanicus |
| Trichobius uniformis | ectoparasiteOf | Sturnira lilium |


you get 

```bash
curl "https://api.globalbioticinteractions.org/taxon/COL:4CP/eats?type=csv"\
 | head -3\
 | mlr --icsv --omd cat
```

| source_taxon_name | interaction_type | target_taxon_name |
| --- | --- | --- |
| Histiostomatidae | preysOn | Protozoa |
| Histiostomatidae | preysOn | Bacteria |

**Comment by nleguillarme** [comment]
> re: interaction types - In my mind, a parasitic interaction is a kind of trophic interactions, because the parasite eats part of their host. Please let me know if you think we should reconsider this inference. Perhaps a "derives nutrients from" would be a more applicable generalization of a parasitic interactions to describe the relationship between the parasite and their host?

Well, as part of our Soil Food Web Ontology, we included (trophic) parasitism as a relation relevant to soil food web modelling (although there exist non-trophic parasitic interactions), so I'd agree with you (and I am also interested in retrieving parasitic interactions from globi, so that's not really a problem to me), although "parasite of" is not a subproperty of "eats" in RO (https://ontobee.org/ontology/RO?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002444).

**Comment by nleguillarme** [comment]
> A quick search on _Trichobius uniformis _ via https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=Trichobius%20uniformis told me that the GloBI Taxon Graph connects
> 
> Trichobius uniformis -> Trichobius -> IRMNG Trichobius Canestrini, 1896 https://www.irmng.org/aphia.php?p=taxdetails&id=1298129
> 
> And, according to IRMNG Trichobius appears to be an uncertain mite genus.
> 
> ![image](https://private-user-images.githubusercontent.com/1084872/356210999-1fed3cda-cab8-4713-ace3-7ce23bd5ca1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTkwNjQsIm5iZiI6MTcyMzExODc2NCwicGF0aCI6Ii8xMDg0ODcyLzM1NjIxMDk5OS0xZmVkM2NkYS1jYWI4LTQ3MTMtYWNlMy03Y2UyM2JkNWNhMWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDhUMTIwNjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWQ0NDhmMGFhNzk0MDA5MGNkZDEwNjBhMGE4MWM1OGU3YWFhYTE4ZTVlMTJhNmJiNTg4MDgwMDdkZWY5ZjhjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NNRWoZwdTYmzc58IcRYC2n_3eVPdR8fxVQ4HEwvXr68)

I understand! Still the same old problem with taxonomic updates ^^"
