### ISSUE TITLE
suggest to index Crayfish pathogen as reported by Ion MC, et al. 2024. World of Crayfish™: a web platform towards real-time global mapping of freshwater crayfish and their pathogens. PeerJ 12:e18229 https://doi.org/10.7717/peerj.18229

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#1023]
@daniel-mietchen noted the following publication

> Ion MC, Bloomer CC, Bărăscu TI, Oficialdegui FJ, Shoobs NF, Williams BW, Scheers K, Clavero M, Grandjean F, Collas M, Baudry T, Loughman Z, Wright JJ, Ruokonen TJ, Chucholl C, Guareschi S, Koese B, Banyai ZM, Hodson J, Hurt M, Kaldre K, Lipták B, Fetzner JW, Cancellario T, Weiperth A, Birzaks J, Trichkova T, Todorov M, Balalaikins M, Griffin B, Petko ON, Acevedo-Alonso A, D’Elía G, Śliwińska K, Alekhnovich A, Choong H, South J, Whiterod N, Zorić K, Haase P, Soto I, Brady DJ, Haubrock PJ, Torres PJ, Şadrin D, Vlach P, Kaya C, Woo Jung S, Kim J, Vermeersch XHC, Bonk M, Guiaşu R, Harlioğlu MM, Devlin J, Kurtul I, Błońska D, Boets P, Masigol H, Cabe PR, Jussila J, Vrålstad T, Beresford DV, Reid SM, Patoka J, Strand DA, Tarkan AS, Steen F, Abeel T, Harwood M, Auer S, Kelly S, Giantsis IA, Maciaszek R, Alvanou MV, Aksu Ö, Hayes DM, Kawai T, Tricarico E, Chakandinakira A, Barnett ZC, Kudor ŞG, Beda AE, Vîlcea L, Mizeranschi AE, Neagul M, Licz A, Cotoarbă AD, Petrusek A, Kouba A, Taylor CA, Pârvulescu L. 2024. World of Crayfish™: a web platform towards real-time global mapping of freshwater crayfish and their pathogens. PeerJ 12:e18229 https://doi.org/10.7717/peerj.18229

At first glance, I fail to see an archived dataset for download.

@Daniel-Mietchen can you confirm?

**Comment by JamesHod-Eco** [comment]
Hi @jhpoelen and @Daniel-Mietchen, I spoke to Daniel about this yesterday as I am one of the co-authors. The reason the database is not archived is as follows "Site access is free, however exact location of crayfish species is restricted to prevent commercial exploitation of sensitive species." This is under the Usage Notes section in the paper if you would like to check yourself. The usage is limited to a simple format for non-registered member of the IAA (see below), which is frustrating but I believe was implemented to prevent either vulnerable native species being exploited, or malicious spread of invasives.

"The platform is open for anyone but there are two layers of users. Non-registered users can view our maps in a simplified format, with a hexagonal overlay covering the exact locations. While this provides a general overview of crayfish distributions, _registered members of the [International Association of Astacology](https://www.astacology.org/) can access more advanced features. This includes downloading maps and generate datasets of geospatial variables specifically customised to freshwater habitats within the framework of global hydrographical network."_ 

I hope that helps clear up the lack of archived database?

Best wishes,

James

**Comment by jhpoelen** [comment]
@JamesHod-Eco Thanks for clarifying the data management related to World of Crayfish. 

Would it be feasible to publish a dataset with fuzzed coordinates? For instance, instead of some lat/lng, you'd include some associated locality name or geonames.org / gadm.org  feature.  

Alternatively, publishing a datasets without the location would be a great start. Then, folks would know that your dataset contains claims about Crayfish pathogens. 

Curious to hear your thoughts.

**Comment by JamesHod-Eco** [comment]
Hi Jorrit,

Sorry for the delay in reply, I think that sounds like a good idea, however given I was involved in the project predominantly as a data contributor, and am not the overall curator/lead on it I cannot guarantee this. I will however send some emails and get back to you asap.

James

**Comment by jhpoelen** [comment]
@JamesHod-Eco Thanks for your response, and looking forward to learning more about ways to index World of Crayfish and your collated database on narrow-clawed crayfish reported locations.

**Comment by parvulescubio** [comment]
Dear Jorrit,
Thank you for your feedback and for showing interest in WoC.

To address your question:
- WoC platform is still in development, and unfortunately, the dataset download functionality hasn’t been implemented yet due to limited programming resources.
- Regarding crayfish data, as James mentioned, members of the International Association of Astacologists (IAA) requested that precise locations remain restricted to the public for conservation reasons. Currently, only hexagonal grid representations are visible, with links to original data sources where available.

We are working on a better data management system to allow different access levels. Currently, IAA members can view exact crayfish locations. If you need pathogen data (only A. astaci is available at the moment), we can provide it upon request, though the dataset has limited coverage. We are actively working to encourage more contributors to help expand this dataset.

**Comment by IonCM** [comment]
Hello all,

As @parvulescubio and @JamesHod-Eco already explained currently there are now downloads available as some data are sensitive. But if I understood correctly @jhpoelen GLOBI project is about species interaction so only pathogen (Aphanomices astaci) and crayfish species would be of interest. I think those spatial points are free from sensitive data and we could find a way to share. Let me a few days to see what the best formula would be. As Lucian said pathogens are now only/mostly at European level but we will increase the database, and potentially include other interactions.

All the best
Mihaela

**Comment by jhpoelen** [comment]
@parvulescubio @JamesHod-Eco @IonCM thanks for sharing your thoughts. 

It'd be great to have GloBI index the crayfish pathogen species interactions with whatever geospatial information you feel comfortable with (or none at all). 

Looking forward, -jorrit

**Comment by jhpoelen** [comment]
@IonCM Thanks for sharing the subset of your  Crayfish dataset. 

Using your xlsx, I've created a first index configuration at https://github.com/globalbioticinteractions/ion2024 for your review.

Also, please see the attached review report zip archive and index.pdf as generated through GloBI's review by Elton. 

[review-report.zip](https://github.com/user-attachments/files/17753307/review-report.zip)
[index.pdf](https://github.com/user-attachments/files/17753332/index.pdf)

Please confirm that the attached index.pdf review report resembles the <400 crayfish pathogen relationship that you shared today.

Thanks!

**Comment by IonCM** [comment]
@jhpoelen Thanks for creating this index/ report.

I think the major problems arise from taking the header of the dataset as an entry (in fact probably 14 entries). There should be 385  crayfish pathogen relationship

From index.pdf and some files in the report I see that:
as Primary Taxa sourceTaxonName appears   Crayfish_scientific_name counted 14 times
as  Associate Taxa targetTaxonName  appears   Pathogen_symbiont_present  counted 14 times

also in the [review-report.zip] in the README file I see a series of "found malformed doi"  but the reported DOI is in fact information from the URL column (we provided an url were doi was unavailable). On a second look I think the URL column was completely scrambled (probably due to empty doi cells)  I have reattached the excel...  Maybe a NA- non available in the empty DOI cells would settle this error?  
[GloBI_interactions.xlsx](https://github.com/user-attachments/files/17754416/GloBI_interactions.xlsx)

Its still unclear to me why there are those 28 invalid date string [Year_of_observation]
Thanks

**Comment by IonCM** [comment]
@jhpoelen if the URL /http introduce some kind of error we could completely ditch that column

**Comment by jhpoelen** [comment]
@IonCM first, apologies for the delay.

Second, I had a look at your observations of the review report. I found that the review method use introduced caused the data to be inconsistent due to unexpected handling of columns with empty values.

I am working on changing a tool used for review (i.e., Preston) to more gracefully handle rows that contain empty fields. 

Thanks for being patient as I am working on this.

**Comment by jhpoelen** [comment]
Hi @IonCM -

After applying an update to Preston, the tool handling xlsx -> tsv transformation, the following review reports were generated. 

[ion-2024-review-report-2024-11-28.zip](https://github.com/user-attachments/files/17952188/ion-2024-review-report-2024-11-28.zip)
which includes

[index.pdf](https://github.com/user-attachments/files/17952194/index.pdf)


Kindly inspect the reports, and let me know if you have any questions.

Thanks again for your patience,
-jorrit

**Comment by jhpoelen** [comment]
@IonCM A version of your Crayfish pathogen data was made available in a recent copy of the GloBI index. 

See screenshot obtained after requesting https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Fion2024&interactionType=interactsWith on 2024-12-04

Please feel free to re-open this issue or comment if you have additional ideas/ concerns or questions about how your data is getting indexed. 

Thanks again for sharing!

![image](https://github.com/user-attachments/assets/926aeb43-4b2f-45a9-8c21-4d0f35182744)

**Comment by IonCM** [comment]
Hi, 
Sorry this last weeks were full. I'll try take a look in weekend.
Hope its all ok

Best 
Mihaela
