### ISSUE TITLE
Sarcophagidae and Mus

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/globalbioticinteractions#414]
@jhpoelen I am seeing some unexpected behavior in the GloBI results. 

If I search (using the web interface) for sourceTaxon Sarcophagidae and targetTaxon Mus I get lots of hits. This is with interaction type "interactsWith"
https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=Sarcophagidae&targetTaxon=Mus

Yet, if I search the opposite I get nothing
https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=Mus&targetTaxon=Sarcophagidae

I would assume interactsWith is bidirectional?

**Comment by jhpoelen** [comment]
After close inspection, the results of https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=Sarcophagidae&targetTaxon=Mus included reported interactions between Sarcophagidae and "Mus*" . Due to some query implementation quirks, the reverse did match against "Mus" and not "Mus*". In order words, the match was a bit too greedy and included implicit wildcard taxon matches.

**Comment by jhpoelen** [comment]
After deploying a fix, the expected results were found - no results for either https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=Sarcophagidae&targetTaxon=Mus and https://www.globalbioticinteractions.org/?interactionType=interactsWith&sourceTaxon=Mus&targetTaxon=Sarcophagidae .

See attached screenshot.
![Screenshot from 2019-11-13 17-16-53](https://user-images.githubusercontent.com/1084872/68818343-915e4b80-0639-11ea-97da-d735f01efcc4.png)

Please comment / re-open if you have remaining issues about this.
