### ISSUE TITLE
index Plazi publications related to bat host associations

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#477]

**Comment by jhpoelen** [comment]
duplicate of #480 #481 #483

**Comment by jhpoelen** [comment]
Re-opening this issue. Indexing Plazi taxonomic treatments is related, but not the same as indexing Pensoft pubs #480 #481 #483

**Comment by jhpoelen** [comment]
for example of using dwc:associatedOccurrences to establish links between specimen see Arctos approach to it at https://www.globalbioticinteractions.org/2019/07/10/associating-with-natural-history-collections/ .

**Comment by jhpoelen** [comment]
follwing discussion with @n8upham @myrmoteras , a proposed workflow for GloBI <> Plazi 

1. periodically, GloBI crawls through all Plazi meta-data
2. GloBI indexes Plazi annotated publications (e.g., taxonomic treatments)
3. researchers use GloBI to find Plazi publication related to, let's say, bat - virus associations
4. researchers not only find Plazi annotated publications, but also related associations sourced from physical (genetic and specimen) evidence datasets.

**Comment by jhpoelen** [comment]
@myrmoteras - is this what you had in mind? If so, please let me know how to best implement steps 1. and 2. If not, please propose alternate.

**Comment by n8upham** [comment]
Prior to step 1, in the context of this NSF grant, would be for Plazi to be doing targeted digitization of literature that is likely to yield host-virus interactions for mammals (e.g., viral surveys, taxonomic literature of both hosts and viruses).  The last step you have is awesome for connecting back to museum data and NCBI sequences

**Comment by myrmoteras** [comment]
@jhpoelen @n8upham here is a more verbose feature request to include host relationships for out discussion within the BLR. 
I would appreciate if you could check whether this is what suits you, especially from the point of view of harvesting

https://docs.google.com/document/d/1cKcQfx8X8uAXR6JF96jqZO8OCpwwkYatnxSIyVXvYbo/edit#

This is an ongoing issue on our side, and we have now to possibility and actually already begun to use custom metdata for the taxonomicTreatments

**Comment by jhpoelen** [comment]
@myrmoteras thanks for sharing the document. I hoping to provide detailed feedback later today, especially around the encoding of the association fields and their values.

**Comment by myrmoteras** [comment]
Hi Nate and Jorrit

Regarding the AI and TDM we have expertise here in my other institution, the Swiss Institute of Bioinformatics. For Covid-19 purposes we just put together a vocabulary that should help to find publications and data therein. https://docs.google.com/spreadsheets/d/1uRtGqYMC_mb1Uj8CRd0g97yHybj1NsmjT0_AH_NYhR8/edit?pli=1#gid=1967553474 

What we would suggest is to look at the following steps:

1. harvest all we can, that is preprints (MedRxiv, BioRxiv, PubMed, other sources). irrespective whether they are as PDF or JATS accessible. use among others access via the [COVID-19 Initiative](https://www.ncbi.nlm.nih.gov/pmc/about/covid-19/#rel-link) 

2. Classify the "value" of the papers in terms of peer-review, preprint, other: 

3. use classifiers to find papers about coronaviruses, hosts

4. extract host names, their interactions, including host/virus but also those indicating food chains (be scavenged, eaten, predated, etc.) 

5. run a search to find articles about the hosts, extract their names, synonyms, vernacular names to run again 3.

6. make sure that all the extracted data is FAIR and open for other researchers (ie add respective metadata, and make as much data accessible eg treatments, figures, maps9

SIB has experience in 1-3 (4). 
Plazi has experience for 3-6

If you have a postdoc at hand, he could also work with the SIB infrastructure, which is very robust. 
Together with SIB and other partners we are submitting a project to build this service (the submission got postponed for 2 months because of Covid-19 due any time soon. Another aspect which might be helpful is that textmining is for legal reasons better done in Switzerland which is more liberal concerning closed access materials.

If you are interested in this step, I will introduce Patrick Ruch at SIB, running the labs.

**Comment by n8upham** [comment]
Hi both,

Donat thanks for sending those details re SIB and the text-mining vocabulary you have already assembled.  This looks fantastic and I can see how it would be highly useful for our purposes of gathering host-virus interaction data — its true that much of that information will be in biomedical literature.

A downside of biomedical literature is that they often don’t fully identify the host animals (i.e., “bat” or “civet” rather than the full scientific name with species ID) — its possible that we can salvage many of these classifications by means of *geocoordinates* for the observations and comparing with host geographic range maps.  “Bat” may be too vague, but "Rhinolophus sp.” is likely salvage-able given a geocoordinate.  Anyway, I mention that because we will ultimately need species-specific data on both viruses and hosts in order to do our targeted analyses.  Is there a way to add additional taxonomic fields to this great Google sheet<https://docs.google.com/spreadsheets/d/1Rq57pmrA3V3k_PrKWGG0Y65-ZN9TRR497lmUu9wx0Cc/edit#gid=0> which you sent?

In general, I’m glad to bring SIB into this collaboration and have them interface directly with the postdoc based at Arizona State.  I’ll send budget ideas in an email.



On Apr 23, 2020, at 11:27 AM, Donat Agosti <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Nate and Jorrit

Regarding the AI and TDM we have expertise here in my other institution, the Swiss Institute of Bioinformatics. For Covid-19 purposes we just put together a vocabulary that should help to find publications and data therein. https://docs.google.com/spreadsheets/d/1uRtGqYMC_mb1Uj8CRd0g97yHybj1NsmjT0_AH_NYhR8/edit?pli=1#gid=1967553474

What we would suggest is to look at the following steps:

  1.  harvest all we can, that is preprints (MedRxiv, BioRxiv, PubMed, other sources). irrespective whether they are as PDF or JATS accessible. use among others access via the COVID-19 Initiative<https://www.ncbi.nlm.nih.gov/pmc/about/covid-19/#rel-link>

  2.  Classify the "value" of the papers in terms of peer-review, preprint, other:

  3.  use classifiers to find papers about coronaviruses, hosts

  4.  extract host names, their interactions, including host/virus but also those indicating food chains (be scavenged, eaten, predated, etc.)

  5.  run a search to find articles about the hosts, extract their names, synonyms, vernacular names to run again 3.

  6.  make sure that all the extracted data is FAIR and open for other researchers (ie add respective metadata, and make as much data accessible eg treatments, figures, maps9

SIB has experience in 1-3 (4).
Plazi has experience for 3-6

If you have a postdoc at hand, he could also work with the SIB infrastructure, which is very robust.
Together with SIB and other partners we are submitting a project to build this service (the submission got postponed for 2 months because of Covid-19 due any time soon. Another aspect which might be helpful is that textmining is for legal reasons better done in Switzerland which is more liberal concerning closed access materials.

If you are interested in this step, I will introduce Patrick Ruch at SIB, running the labs.

**Comment by jhpoelen** [comment]
@myrmoteras @n8upham closing this initial issues: the comments have been absorbed in upcoming proposal and related issued #487 #490 #488 . Please re-open if issues remain.
