### ISSUE TITLE
Suggest to index Pollinator Database

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/globalbioticinteractions#501]
https://saveplants.org/2017/12/28/pollinator-database/

**Comment by jhpoelen** [comment]
@seltmann I've prepared a first pass at configuring GloBI to index CPC (or saveplants.org) pollinator database at https://github.com/globalbioticinteractions/cpc-pollinators .

Please note that the saveplants.org download link produces a zip file with a date dependent file in it. For now, I've manually extracted a copy and put them into the config github repo. Also, I've prepared a first interaction type mapping. 

Please review if you get the chance. 

I am hoping to wait until the pollinator/visitor records propagate before replying to Katie of CPC, so that she'll have something to review and at poke at.

**Comment by jhpoelen** [comment]
The cpc polllinator records have propagated. See attached screenshot related to https://www.globalbioticinteractions.org/?accordingTo=globi%3Aglobalbioticinteractions%2Fcpc-pollinators&interactionType=ecologicallyRelatedTo . 
![Screenshot from 2020-06-08 11-55-29](https://user-images.githubusercontent.com/1084872/84069261-2088d300-a97f-11ea-8a6e-7d09d9797ffc.png)

**Comment by jhpoelen** [comment]
At quick glance, CPC pollinators include over 16k pollination/flower visit records involving over 3.5k taxa.
