### ISSUE TITLE
eventDateUnixEpoch not populated when an exact date is not specified

### ISSUE THREAD

**Issue by qgroom** [globalbioticinteractions/globalbioticinteractions#506]
When a observationDateTime is supplied as a year or date range the eventDateUnixEpoch is left unpopulated when imported into GloBI.
An example is the data supplied for Rousettus aegyptiacus interacting with Ficus carica from Mammari, Cyprus in the dataset https://github.com/qgroom/batinterations. This record was submitted with the date range 2009-07-23/2010-03-16

Another example is the data supplied for Rousettus aegyptiacus interacting with Arbutus andrachne at Mount Carmel National Park, Israel. This record was submitted with the date of 2008.

**Comment by jhpoelen** [comment]
@qgroom thanks for reporting the date issue. I was able to reproduce and fix this issue. It turned out that observationDateTime wasn't being mapped properly. Note that for date ranges, the start date of the range is used currently to facilitate downstream analysis. If you have any ideas on how to improve the range mapping, please open a separate issue.

**Comment by jhpoelen** [comment]
see also related datetime issue #439

**Comment by jhpoelen** [comment]
fix implemented and released via v0.17.3 https://github.com/globalbioticinteractions/globalbioticinteractions/releases/tag/v0.17.3 .
