### ISSUE TITLE
Formatting dates in Darwin Core

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/globalbioticinteractions#535]
@jhpoelen how would you format the http://rs.tdwg.org/dwc/terms/eventDate for July-August 2006? We entered as 2006-07/08 but receiving a report "176 date range [2006-07/08] appears to start after it ends"

Transferred from https://github.com/globalbioticinteractions/bee-interaction-database/issues/5

**Comment by jhpoelen** [comment]
@seltmann thanks for transferring the issue. I've reproduced the issue and implemented a workaround for the inability for joda (a datetime parsing library) to parse the valid iso9601 intervals you are using in your library. 

The changes should be included in the next release of elton. I'll keep this issue open until you can verify expected behavior using the new elton release.

**Comment by jhpoelen** [comment]
in build https://travis-ci.com/github/globalbioticinteractions/bee-interaction-database/builds/189563053 , we still found:

```
    176 date range [2006-07/08] appears to start after it ends.
```

after upgrade to elton v0.10.3 ,  no such false review note was found in an automated review  https://travis-ci.com/github/globalbioticinteractions/bee-interaction-database/builds/189585585 .

**Comment by jhpoelen** [comment]
@seltmann thanks for being patient!
