### ISSUE TITLE
Changes in the Interactions API

### ISSUE THREAD

**Issue by Rodrigo-A-Pereira** [globalbioticinteractions/globalbioticinteractions#590]
Hi, I noticed that in the last hour there seems to have been a large change in the interactions API, and the interaction results seem to have changed greatly. I would like to know what kinds of changes have been made if possible.

Regards,
Rodrigo Pereira

**Comment by jhpoelen** [comment]
Hey Rodrigo - 

Thanks for you message. The GloBI API provide a dynamic snapshot into often dynamic datasets that are continually indexed. So, if you are using the API instead of the stable/release GloBI data products (see https://globalbioticinteractions.org/data), changes are expected. 

However, I expect most changes to be gradual, so I am curious to hear more about what you've observed:

Can you please be more specific about the big changes that you've noticed?

**Comment by jhpoelen** [comment]
I did notice that the indexes where most recently refreshed at Tue Jan 19 21:57:34 CET 2021 .

**Comment by Rodrigo-A-Pereira** [comment]
Hi @jhpoelen thanks for the quick reply :)

I am working mostly with "hasHost" interaction types. The most notable changes i have noticed, are:

The difference in "targets" returned. Taking as an example the NCBI:418103 (wich is one of the few entities i have a JSON response of the "old" api), the intersection between the old results and new results (this intersection was made taking into account "target_taxon_name" and "target_taxon_external_id") is only of 11 out of the 298 and 878 unique entities of both the old and new responses respecively. 

Additionally i also noticed that there was a large introduction of entities with no match to external databases (EOL, NCBI, etc ), with the old api returning 15 entities with "no:match" on the "target_taxon_external_id" field , while the new api returns 652 such entities.


Once again thank you so much for the quick reply,

Best regards,
Rodrigo Pereira

**Comment by jhpoelen** [comment]
Thanks for providing more details on the changes you noticed. Can you please include the before and after data in text format? This way, I can go over the changes in more details and figure out whether the behavior is expected or not.

Thanks for being patient.

**Comment by Rodrigo-A-Pereira** [comment]
Sure, here are the old and new versions of response of the two entites i still have the response from the old API ( NCBI:418103 and NCBI:6231).

[newNCBI6231.txt](https://github.com/globalbioticinteractions/globalbioticinteractions/files/5839157/newNCBI6231.txt)
[newNCBI418103.txt](https://github.com/globalbioticinteractions/globalbioticinteractions/files/5839158/newNCBI418103.txt)
[oldNCBI6231.txt](https://github.com/globalbioticinteractions/globalbioticinteractions/files/5839159/oldNCBI6231.txt)
[oldNCBI418103.txt](https://github.com/globalbioticinteractions/globalbioticinteractions/files/5839160/oldNCBI418103.txt)


Here is also the python code i used to obtain the statistics i gave in my previous message, if it is usefull (needs to convert attached files to json format since Githug does not accept json files):

```
import pandas as pd
import json

#Load Json files
oldf = open('oldNCBI418103.json') 
newf = open('newNCBI418103.json')
oldJson=json.load(oldf)
newJson=json.load(newf)

##Old response statistics
olddf=pd.DataFrame(oldJson["data"], columns=oldJson["columns"])
olddf=olddf[["interaction_type","target_taxon_name","target_taxon_external_id"]].sort_values(by=['target_taxon_name']).drop_duplicates()

print(f"Number of unique rows in old response: {olddf.shape[0]}")
print("Number of 'no:match' in old response: {0}".format(olddf[olddf['target_taxon_external_id']=="no:match"].shape[0]))

##New response statistics
newdf=pd.DataFrame(newJson["data"], columns=newJson["columns"])
newdf=newdf[["interaction_type","target_taxon_name","target_taxon_external_id"]].sort_values(by=['target_taxon_name']).drop_duplicates()

print(f"Number of unique rows in old response: {newdf.shape[0]}")
print("Number of 'no:match' in new response: {0}".format(newdf[newdf['target_taxon_external_id']=="no:match"].shape[0]))

##Intersection
print("Intersected entities: {0}".format(olddf.merge(newdf, how = 'outer' ,indicator=True).loc[lambda x : x['_merge']=='both'].shape[0]))
```

**Comment by jhpoelen** [comment]
Thanks for providing the details Rodrigo! Hoping to get back to this soon. If you don't hear from me soon, please feel free to remind me!

**Comment by jhpoelen** [comment]
Hi @Rodrigo-A-Pereira -

I had another look at your reported issues. The root cause is not that the results changed, but that the ordering of the results in not guaranteed. Also, you are hitting the request page limits of 1024. 

So, in order to compare results, you have to 1. retrieve *all* results using pagination (see https://github.com/globalbioticinteractions/globalbioticinteractions/wiki/API#pagination ) and then 2. sort the results before comparing them. 

For your examples oldNCBI6231 and newNCBI6231 I confirm that you were hitting the page limits by counting the individual data rows for the json results using:

```
$ curl -L "https://github.com/globalbioticinteractions/globalbioticinteractions/files/5839159/oldNCBI6231.txt" | jq -c .data[] | wc -l
1024
```
and 

```
$ curl -L "https://github.com/globalbioticinteractions/globalbioticinteractions/files/5839157/newNCBI6231.txt" | jq -c .data[] | wc -l
1024
```

To avoid having the use page limits, you can just get all the data via ```interactions.tsv.gz``` at https://globalbioticinteractions.org/data and filter down the results to suit your research. If you choose the use the stable data, you won't have to worry about updates.  

Alternatively, if you decided to stick with the web api, you'll have to page through all the results until no more rows are generated. See https://github.com/globalbioticinteractions/globalbioticinteractions/wiki/API#pagination for more information on that. 

I believe that resolves your issue. Please comment / re-open if this is not the case.

Thanks for being patient and am curious to hear how you'll end up using the rich species interactions datasets provided by the many GloBI data sources https://globalbioticinteractions.org/sources .

**Comment by Rodrigo-A-Pereira** [comment]
Hi @jhpoelen, thank you for replying. 
I ended up using the `interactions.tsv.gz` like u sugested given its stability.
