### ISSUE TITLE
a dataset failed to ingest

### ISSUE THREAD

**Issue by ninacourlee** [globalbioticinteractions/globalbioticinteractions#722]
Dear colleagues,
i have uploaded my first test dataset (after a course kindly organized by Jorrit at https://www.globalbioticinteractions.org/deadwood2021/),
i tried to follow the instructions, but the ingestion failed, and i couldn't find the cause.
Please, would you be kind to look into it and give me the feedback what could go wrong here:
https://github.com/ninacourlee/Andromeda-polifolia-fungal-consortia

**Comment by jhpoelen** [comment]
@ninacourlee hey nina - great you last week. Also, nice to "meet" you bog data now! 

> i tried to follow the instructions, but the ingestion failed, and i couldn't find the cause.

As far as I can tell, your data is configured nicely for indexing by GloBI in https://github.com/ninacourlee/Andromeda-polifolia-fungal-consortia . So I am not quite sure what do you mean by "the ingestion failed". Can you please elaborate ? 

I did notice that your zenodo publication at  looks a little different than what I am used to. Did you use the GitHub-Zenodo integration to make your dataset citable? If not, you might want to have a look at https://guides.github.com/activities/citable-code/ . 

Please also note that is may take some days for your dataset to appear on https://globalbioticinteractions.org .

**Comment by ninacourlee** [comment]
Dear Jorrit @jhpoelen , 

Thank you for the fast response, 

> As far as I can tell, your data is configured nicely for indexing by GloBI in https://github.com/ninacourlee/Andromeda-polifolia-fungal-consortia . So I am not quite sure what do you mean by "the ingestion failed". Can you please elaborate ?

That is because i received a message in my email with this link https://github.com/ninacourlee/Andromeda-polifolia-fungal-consortia/actions/runs/1399196036
from this i concluded that the ingestion failed.. am i wrong?

> I did notice that your zenodo publication at looks a little different than what I am used to. Did you use the GitHub-Zenodo integration to make your dataset citable? If not, you might want to have a look at https://guides.github.com/activities/citable-code/ .
 
Sorry, this archive is redundant, i was playing around in a wrong direction and created Zenodo archive before GitHub.
Now i was following the instruction (https://guides.github.com/activities/citable-code/) and made successfull integration of my GitHub repository into Zenodo, and added a DOI. It should be ok now? https://doi.org/10.5281/zenodo.5632779

Nina

**Comment by jhpoelen** [comment]
Hey Nina - thanks for your message. As far as I can tell your recent changes made the review pass!

You were correct that the one run failed, but after you re-added the ```interactions.tsv``` file, the review passed:

https://github.com/ninacourlee/Andromeda-polifolia-fungal-consortia/runs/4048199565?check_suite_focus=true

from https://github.com/ninacourlee/Andromeda-polifolia-fungal-consortia/runs/4048199565?check_suite_focus=true#step:4:39 - 

```Hurray! [ninacourlee/Andromeda-polifolia-fungal-consortia] passed the GloBI review.```

Currently, you only get an email on failure. On success, you do not get an email. 

Please let me know if there's anything you think we can do to make it a little easier to get datasets indexed in the future.

**Comment by jhpoelen** [comment]
btw - If you'd like to get an email on all completed actions, not just failed ones, you can configure this in your account settings: settings > notifications > actions .

By default it only sends email on failed actions (e.g., when GloBI's review results in review notes)

See attached screenshot. 

![Screenshot from 2021-10-31 13-55-56](https://user-images.githubusercontent.com/1084872/139601023-3858e870-af78-4d65-a124-85ac5db28525.png)

**Comment by jhpoelen** [comment]
@ninacourlee just checked https://globalbioticinteractions.org and found that your bog interaction datasets has been indexed. 

Please feel free to close this issue if you are happy with the results. Otherwise, I'd be happy to hear your comments.

Note that GloBI picked up your initial names for the repository: I've made sure that these intermediate names will no longer be visible in future versions of GloBI's search index.

See https://www.globalbioticinteractions.org/?accordingTo=globi%3Aninacourlee%2FAndromeda-polifolia-fungal-consortia&interactionType=ecologicallyRelatedTo and https://www.globalbioticinteractions.org/browse/?accordingTo=globi%3Aninacourlee%2FAndromeda-polifolia-fungal-consortia&interactionType=ecologicallyRelatedTo&resultType=json for associated screenshots. 

![Screenshot from 2021-11-01 10-02-48](https://user-images.githubusercontent.com/1084872/139710745-e299fb51-fda9-4953-bdda-aad0db9fb3d9.png)
![Screenshot from 2021-11-01 10-02-40](https://user-images.githubusercontent.com/1084872/139710754-0ebb2a43-52ea-4de7-a0f7-9d8e75ad4b4e.png)
![Screenshot from 2021-11-01 10-01-45](https://user-images.githubusercontent.com/1084872/139710764-61e47de2-e097-42bf-9873-37276d25f4cc.png)

**Comment by ninacourlee** [comment]
Thank you for your assist Jorrit!
If i could ask one question, not related to this issue?
I have just received a dataset from my colleague and published it on GBIF, it has records of nematode parasites on amphibia. We used "assotiatedTaxa" to accomodate host-parasite interagions in GBIF.
Do you think that i could upload this dataset to GloBI as well, or you will eventually receive these data from GBIF? I don't know if there is exchange of data between GloBI and GBIF.
The dataset: https://www.gbif.org/dataset/17af9dde-6387-4247-afda-faa26a572a08

**Comment by ninacourlee** [comment]
Dear Jorrit, 
please could you explain a little bit more about this indexing of our IPT,
will this be once, or we need to update this information periodically upon request, also which datasets or fields you are indexing?
I suppose that GloBI would need 'associatedTaxa' field for organisms interactions data. But so far it is only one of our datasets which has this field. I could export associatedTaxa field from our Fungarium collection database, which is in Specify, but it wasn't mapped for export in GBIF so far.

**Comment by jhpoelen** [comment]
@ninacourlee thanks for asking about how GloBI indexes IPTs.

The GloBI configuration at https://github.com/globalbioticinteractions/ysu-bc/  to index your IPT is used by GloBI to periodically (~weekly) update and index the related datasets. 

No need to do anything on your end - GloBI will try to index the data. Hoping you can have a look once the first index cycle has completed. I'd be curious to hear whether GloBI's interpretation of your data makes sense to you. 

>I suppose that GloBI would need 'associatedTaxa' field for organisms interactions data. 

Aside from 'associatedTaxa', GloBI also looks at fields like associatedOccurrences, the Resource Relations extension, remarks, habitat etc. And, we can add support for other methods if desired.

>  I could export associatedTaxa field from our Fungarium collection database, which is in Specify, but it wasn't mapped for export in GBIF so far.

Mapping your fungal interactions from your Fungarium collection database into fields that GloBI understands would be great! I am curious to learn more about your datasets and the type of interactions they describe.

 Note that in collaboration with Arctos foiks like @dustymc @Jegelewicz @campmlc
, we've even figured out ways to link specimen-to-specimen across collections. So, if you have specimen for both interacting organisms, I'd be curious to find ways to link those on the specimen level, instead of the less specific taxon level. Would be fun to do something similar with your collections!

Curious to hear your thoughts

**Comment by jhpoelen** [comment]
@ninacourlee your IPT datasets have been indexed/reviewed by GloBI. 

Now, also the review report is available via:

https://depot.globalbioticinteractions.org/reviews/globalbioticinteractions/ysu-bc/README.txt 

Please feel free to re-open this issue, or share comments if you feel that your data records should be interpreted / indexed differently. 

Thanks for your communication, and hoping to hear from you at some point.

**Comment by ninacourlee** [comment]
Dear Jorrit, thank you a lot and sorry for the delay.

I checked the indexing of the data from our IPT, it seems that only two datasets were indexed now, but there are more to be indexed. I wonder why other datasets wouldn't be indexed:

1) http://ipt.ugrasu.ru:8080/ipt/manage/resource?r=amphibiaparasites This dataset wasnt' indexed, perhaps because i used associatedOrganisms instead of associatedTaxa field. Would you recommend to use only associatedTaxa for taxon/parasite interactions?  If so, i will correct this.

2) http://ipt.ugrasu.ru:8080/ipt/manage/resource?r=lizardmites This dataset was indexed fine, it has associatedTaxa field and looks good in Globi  [example Zootoca viviparia|host of|Trombiculidae Ewing]

3) http://ipt.ugrasu.ru:8080/ipt/resource?r=fredy This dataset was indexed by "habitat" field, but i don't think that it is the right field for "species interactions". There is no specific interactions between organisms in this field, only desciprtion of habitat and substrate. GloBI uses "related to" interaction type and related the species to description of its habitat. Do you think that this information has sense for Globi?  [example Inocybe perlata|relate to|soil among mixed litter and moss]

4) http://ipt.ugrasu.ru:8080/ipt/manage/resource?r=fungariumysu This dataset wasn't indexed, but it has the same field "habitat", i wonder why 3) was indexed and 4) wasn't. Anyway, as above, i don't think that this field has sense for Globi.
This dataset is exported from our Specify installation and i have added a new field now to the export >> associatedTaxa. I formatted this field according to DwC from two fields (interaction type and host taxon) [interaction type:Scientific Name]. I imported GloBI vocabulary for interaction types, so that it should be ok for the indexing in the future. For now, i filled in this field with unspecific interactions (interacts with), but i will elaborate this information later (parasitizes, hosts, is symbiont of, etc.). This is the most important thing about species interactions in our database and i look forward it to be indexed by GloBI in the future. 

Other datasets in our IPT don't have meaningful species interacitons information, but i will look forward to add this information  when possible in the future. Please, clarify which field is the most reliable for species interactions > associatedTaxa i guess?

Nina
