### ISSUE TITLE
Inconsistent search results between methods for finding interactions between 2 specified taxa

### ISSUE THREAD

**Issue by H-Waters** [globalbioticinteractions/globalbioticinteractions#799]
Hi! 

Apologies if this isn't the right place for this kind of issue, but I can't figure what's going on.

When searching for interactions between two example taxa (_Ranunculus_ and _Malachius bipustulatus_), I get different results using  `get_interactions_by_taxa()` depending on whether I: 1) specify both taxa, as source and target respectively, or 2) only specify the source taxon, and then filter the returned df by the name of the target taxon. Confusingly, method 1) actually returns more results than method 2). 

Method 1) returns 6 rows. It gets interactions between _M. bipustulatus_ and _Ranunculus_, _Ranunculus repens_, and _Ranunculus acris_:
```
twoTaxa <- get_interactions_by_taxa(sourcetaxon = "Ranunculus", targettaxon = "Malachius bipustulatus",
                         bbox=c(-180, 0, 180, 90 ))
nrow(twoTaxa) 
```
Method 2) returns only 1 row. The interaction is between _M. bipustulatus_ and _Ranunculus repens_:
```
oneTaxa <- get_interactions_by_taxa(sourcetaxon = "Ranunculus", 
                         bbox=c(-180, 0, 180, 90 ))
oneTaxa <- oneTaxa[oneTaxa$target_taxon_name == "Malachius bipustulatus",]
nrow(oneTaxa)
```

Why doesn't method 2), which superficially seems like the 'wider query', grab the same rows that are in method 1)? Why doesn't method 2) also capture the links between _M. bipustulatus_ and _Ranunculus_/_Ranunculus acris_?

Thanks!

**Comment by jhpoelen** [comment]
@H-Waters thanks for sharing your observations re: rglobi interactions. 

I was able to produce:

```R
> twoTaxa <- get_interactions_by_taxa(sourcetaxon = "Ranunculus", targettaxon = "Malachius bipustulatus", bbox=c(-180, 0, 180, 90 ))
> nrow(twoTaxa)
[1] 6
```
and

```R
> oneTaxa <- get_interactions_by_taxa(sourcetaxon = "Ranunculus",  bbox=c(-180, 0, 180, 90 ))
> oneTaxaSubset <- oneTaxa[oneTaxa$target_taxon_name == "Malachius bipustulatus",]  
> nrow(oneTaxaSubset)
[1] 1
```

The reason why you are getting the confusing results, is due to a paging artifact. 

rglobi is using the GloBI Web API, and Web APIs are usually configured to only return a limited amount of results at a time. 

In this case, 

```R
> nrow(get_interactions_by_taxa(sourcetaxon = "Ranunculus",  bbox=c(-180, 0, 180, 90 )))
1024
```

indicating that the default maximum number of results (e.g., 1024) has been reached. So, yes, the second query is a wide query, but runs into a Web API limit, and cannot include all the additional 5 records reported for _Malachius bipustulatus_ . 

This Web API limit is a bit of a bummer, and highlights that the Web API is really just there to discover data. If you'd like to work with all the data, I usually use the interactions.tsv.gz or interactions.csv.gz instead of working around the Web API constraints. 

If you do want to continue using the rglobi (and therefore GloBI Web API) please have a look at the "paging" section in the rglobi vignette at https://cran.r-project.org/web/packages/rglobi/vignettes/rglobi_vignette.html . See also screenshot below.

![Screenshot from 2022-07-12 16-56-20](https://user-images.githubusercontent.com/1084872/178602428-567ebbf2-b76e-4b7f-a7ee-535695520cf0.png)

Apologies for the inconvenience, I realize that pagination business is a bit of a bummer. 

Am open to suggestions on how to have your future self or your peers getting misled by confusing rglobi outputs due to pagination / web api constraints. 

If this resolved your issue, please close this issue. Otherwise, I'd be happy to continue our conversation.

thanks for your patience!

**Comment by H-Waters** [comment]
Hi @jhpoelen! Thanks so much for taking time to reply to this, and in such detail.

Of course, I had completely forgotten about the results limit. That clears things up! I'll close the issue.

Re: suggestions - I don't know whether you or others would consider it valuable, but perhaps a warning message when a query you've performed has returned more results than the limit would be helpful? 

Thanks again for your help!

**Comment by jhpoelen** [comment]
see https://github.com/ropensci/rglobi/issues/44
