### ISSUE TITLE
manage discoverable EOL collections to summarize diet of popular taxa

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#80]
as discussed with @jhammock and @JRice

EOL provides a way to group taxa into collections. To take advantage of search engines (e.g. EOL internal, google, bing, yahoo), GloBI will automatically create and update collections using a (not yet existing) EOL Collections API for popular taxa and their diet. 

For example, for the popular taxon page "Seals", a collection will be created that includes a list of all prey items of predator taxa belonging to the true seals (Phocidae) family. The description of the collection includes text like: "What do seals eat", "Seal food", "Seal diet" or any other phrase that is commonly used to look up the what a seal eats using a search engine.

**Comment by jhammock** [comment]
Hi, all! I created a collection to represent what our immediate use case (GloBI II, checklist generator) for the collections write api would be: http://eol.org/collections/113457  (seal food!) These needs are pretty modest, no annotations, no order, no objects other than taxa. It does have a collection description. I remember asking for a collection metadata field that could be invisible, but looking at it now I don't really need to hide the description text. It's kind of nice/descriptive. I tried searching for it too, and a pleasing array of substrings fetch this collection pretty well. 

Jeremy, are you comfortable firming up instructions for what you'd like us to feed the write API? What do you think of imitating the API output? (http://eol.org/api/collections/1.0/113457.json?page=1&per_page=300) 

Thanks!

Jen

**Comment by JRice** [comment]
Yes... if you give me a few days to think about it and work on it!  :D

(BTW: Good stuff! Thanks.)

**Comment by jhpoelen** [comment]
Thanks for sharing example @jhammock .

At quick glance, GloBI should be able to generate most information elements in the http://eol.org/collections/113457.json response. 

Currently, the example contains the following description:
```
what do true seals eat? what do seals eat? what do phocids eat? phocid prey seal prey true seal food true seal prey
```

parsing this would be:
```
what do [preferred common name] [interaction type name]? what do [part of preferred common name] [interaction type name]? what do [xxxx] [interaction type name]? [xxxx] [interaction target name] [part of preferred common name] [interaction target name 2] [common name] interaction target name]
```
I am assuming that ```phocids``` is another way to writing the scientific name ```Phocidae```. Is there some existing translation rule I can use to phocidae or similar to phocids or similar? Is it as simple as replacing the ```ae``` with ```s```?

**Comment by jhammock** [comment]
Thanks, Jeremy! 

Jorrit: yeah, generating the "Phocids" style names may be a several iteration exercise. It'll depend on which rank the taxa are for which we want to create these collections, and some are probably more uniform in that sense than others. Which brings me to the previous task- generating that list of taxa. Let me paw through your summarized (EOL) GloBI resource taxa file and think about that; I'll try to say something useful on this subject tomorrow...

**Comment by jhpoelen** [comment]
@jhammock I took some time to write a first pass at automatically generating a collection title and description. One thing I created was a list of expected "commonized" taxon names (e.g. Phocidae -> phocids). I am hoping that you can help extend this list to include a good sample to cover most cases. You can find the list [here](https://github.com/jhpoelen/foragus/blob/master/src/test/resources/name-test.csv). I've added you as a collaborator to the github repo, so you should be able to edit the file directly in the github web interface. 

Another thing I made is a test for the title and description generation. Using common name, scientific name (taxon name) and interaction type, I was able to generate:
```json
"title": "True Seal Food"
"description": "what do true seals eat?
what do phocids eat?
what do true seals prey on?
what do phocids prey on?
what do true seals hunt?
what do phocids hunt?
true seal prey
phocid prey
true seal food
phocid food"}
```

Some questions to help me move forward:

1. please let me know if you are able to edit the list of expect "commonized" names and whether it makes sense to have you extend the list to include most common cases.
2. does the title and description generation for Phocidae make sense? I wasn't able to include the term ```seal``` because this is actually not a common name used for Phocidae.

**Comment by jhammock** [comment]
Looks like I have access. Do you need just the based-on-the-latin commonized names in there? These usually only occur at family or higher, I think. Still wrapping my brain around how this pattern works, but in any case the list is not terribly long at the high ranks.

**Comment by jhammock** [comment]
I think I have a slightly better idea: Can you rely on our API (or Jeremy's new dump) for common names? I can just figure out what these are and add them in a one time resource. You'll want to use other common names too, after all. We may need to figure out if we need to draw the line somewhere on how many common names to use, but I think it might be fine to use them all.

**Comment by jhammock** [comment]
revised sample collection info:

{"title": "True Seal Food",
"description": "what do true seals eat?
what do phocids eat?
what do phocidae eat?
what do true seals prey on?
what do phocids prey on?
what do phocidae prey on?
what do true seals hunt?
what do phocids hunt?
what do phocidae hunt?
true seal prey
phocid prey
phocidae prey
true seal food
phocid food
phocidae food"}

**Comment by JRice** [comment]
So I've been working on the write API (sometimes it's easier to just *do*
it, sometimes it's easier to think about it; since there are technical
hurdles, this turned out to be one of the former).

The good news is twofold: First, this isn't going to be all *that* hard. A
little hard. ...But not too bad. Second, Dima tells me SSL shouldn't be
hard to add once we move the servers (about a month from now). We don't
need to wait for that, but I thought I'd mention it. Yay!

The bad (kinda) news is: it won't be using the old API. At all. Good
riddance (well, the old API will be *around,* but deprecated). It will be
using a much more "Railsy" interface. So the params will be a little
different.

I haven't ironed out what a write will look like, but there are a few
things I can tell you in advance:

A) Because I want to keep the old API around, I have to give this a new
name. So, for now, it's "wapi" (for "write API"). ...A little silly, but
memorable, at least. :\
B) You'll want to pass the version of the API (wapi?) you're using in the
headers, using something like "Accept: application/vnd.eol_wapi.v1" (for
version 1 of the API). This will keep things stable, so I can work on new
features without breaking your code.
C) You'll need to pass your user's api_key in the header as well, with the
"Authorization" key, and it's encrypted. I'm not sure what this looks like
in PHP, but in Rails, this looks something like this (YMMV):

get 'http://eol.org/wapi/collections', {}, { "HTTP_AUTHORIZATION" =>
HttpAuthentication::Token.encode_credentials("1234123") }


It's a little more elegant (if redundant) with curl:

curl http://eol.org/wapi/collections -H 'Authorization: Token
token="1234123"'


Errr... please note neither of these actually work today, since I'm
actually using a local URI, not eol.org. I'm just showing what it might
look like. :\

...We will (eventually) set up a testing environment to make sure this
works.
D) Again, I haven't finished this, but the params will look more like a
typical Rails API, so the params will probably be *something** like this
(pretending it's JSON for clarity):

collection:{name:"Something cool",description:"lots of important stuff
here",collection_items:[{"annotation":"Something
interesting","collected_item_id":75,"collected_item_type":"TaxonConcept","sort_field":"12"}]
}


More info as I have it; sorry for the delay / thanks for being patient!

* Like I said, I still need time to iron this out...

**Comment by jhpoelen** [comment]
@JRice thanks for your update. All sounds pretty good. Would it be easier if I simply put a batch of collections expressed in json in a public place for eol to consume? This would mimick the current harvest strategies for content providers. In a way, I can argue that collections is "meta" content: collections of associated taxa. Would this approach help simplify the development effort?

**Comment by JRice** [comment]
Sorry, I was moving last week, didn't have time to respond until now. :\

No, ingesting a JSON file wouldn't actually be any easier to implement than
exposing an API. Thanks for the thought, though. ...And, honestly, I'm not
a huge fan of our content harvesting strategy, so it's not something i want
to mimic at the moment. :D

**Comment by jhammock** [comment]
Thanks, J! Good to know.

Yikes- you moved in the storm? Go take a nap.

**Comment by jhpoelen** [comment]
@JRice @jhammock I've created a project called [foragus](https://github.com/jhpoelen/foragus). This is  a little tool that queries (or forages) GloBI and builds eol collections from a list of provided popular eol page ids.

Currently, the collections are generated whenever a file [popular_eol_page_ids.csv](https://github.com/jhpoelen/foragus/blob/master/src/test/resources/popular_eol_page_ids.csv) is updated. The resulting collection json files are published to s3 (until eol write api is available). To access these json files, go to https://travis-ci.org/jhpoelen/foragus and scoll down the log window. Here you should see stuff like:

```
INFO: uploading: /home/travis/build/jhpoelen/foragus/target/34543.json (size: 3.9KB)
download_url: https://globi-travis.s3.amazonaws.com/jhpoelen/foragus/24/24.1/target/34543.json

INFO: uploading: /home/travis/build/jhpoelen/foragus/target/7666.json (size: 131KB)
download_url: https://globi-travis.s3.amazonaws.com/jhpoelen/foragus/24/24.1/target/7666.json

Done uploading artifacts
```
Not quite as user friendly as EOL collection pages, but it would allow you to play around with the different page ids: add / remove page ids from  [popular_eol_page_ids.csv](https://github.com/jhpoelen/foragus/blob/master/src/test/resources/popular_eol_page_ids.csv) by clicking "edit"/"save" in the GitHub webpages, wait for a couple of minutes and you should see a new batch published on [travis](https://travis-ci.org/jhpoelen/foragus).

@jhammock - do the collection json file contains the name, description that you were hoping to get?

@JRice - is the format of the collection json ok? 

PS If this is approach too geeky, please do let me know, and we'll figure out a different way to play around with this gadget.

**Comment by jhammock** [comment]
The collection info looks lovely, thanks, Jorrit. Everything I need is in there, plus "sort_field":"12" on every item. I'm mildly curious what that's for.

**Comment by jhpoelen** [comment]
@jhammock glad to hear that the name, descriptions and items looks good!

@JRice is it okay to remove the ```sort_field ```. I added it in there, because it was in your example.

**Comment by jhammock** [comment]
Ah- Other users may find sort field useful for writing to collections, of course. But I don't think we need it for the interactions collections...

**Comment by JRice** [comment]
(In a meeting, sneaking in quick answer:)

Yes, you can remove the sort_field, it is *not* required.

**Comment by jhpoelen** [comment]
@mariestuder - thanks for your feedback in our meeting earlier today . . . could you please provide detailed on how you'd like to the link the collection description to the relevant trait pages?

**Comment by mariestuder** [comment]
I think the consensus was that the Collection Description should be linked to the Data Tab on a taxon page, rather than the Overview Tab.  The Data Tab contains information more specifically of interest to a user looking at, or wanting to use, the interaction data.  

If others agree, we could come up with language in the Collection Description that informs users that by following the link, they will land on the Data Tab and they can scroll down to the Ecology section to find more information and data on interactions.

**Comment by jhpoelen** [comment]
@mariestuder Thanks for sharing - I agree this link to the data tab of the taxon page would be useful. 

My suggested language for the additional description would be:

```
Please visit the <a href="http://eol.org/pages/7666/data">True Seals (Phocidae) data page</a> for more detailed information.
```

Would this be sufficient?

**Comment by mariestuder** [comment]
@jhpoelen I think that should cover it.  Unless we also want to specify that they can also find additional information (will they?  will there be other sources of interaction data found on the data tab that are not in the Collection?).

If they will find "new", additional information then we might tweek the language to say:  Please visit (link) data page for more detailed information and data from other sources.

**Comment by jhammock** [comment]
I dig it, but I think the hint that they'll find other stuff is also a good idea. Not so much non-GloBI interactions data (there's almost none of that) as other traits/attributes about Phocidae...

**Comment by jhpoelen** [comment]
Sounds good. Should we make this implied "from GloBI" assumption explicit by saying:

Please visit (link) data page for more detailed information and data from sources other than GloBI (link to GloBI).

Agree?

**Comment by mariestuder** [comment]
Humm.  That now brings up two thoughts:
 1.  I like the explicit GloBI shout out.  It makes it very clear to the user where the source of the Collection.

2.  I like Jen's comment clarifying that the user can find other trait data.

Maybe as the intro to the Collection, we say something like:  This collection of (interaction) data was automatically generated from (or supplied by, etc) the GloBI database (or project) (link).  Please visit (link) data page for more detailed information about the GloBI interaction data and to find other trait data for Phocidae.

**Comment by jhammock** [comment]
+1

**Comment by jhpoelen** [comment]
I've updated the collection generation tool. For bears (Ursidae), the following description was generated:

_This collection was automatically generated from [Global Biotic Interactions](http://globalbioticinteractions.org)</a> (GloBI) data. Please visit [this data page](http://eol.org/pages/7664/data) for more detailed information about the GloBI interaction data and to find other trait data for Ursidae.
what do bears eat?
what do ursids eat?
what do ursidae eat?
what do bears prey on?
what do ursids prey on?
what do ursidae prey on?
what do bears hunt?
what do ursids hunt?
what do ursidae hunt?
bears prey
ursid prey
ursidae prey
bears food
ursid food
ursidae food_

Please let me know if you have more suggestion to improve this (auto-generated) description.

**Comment by mariestuder** [comment]
This looks great to me, although I have one additional change.  Can you please add "EOL" before "this data page"?  Like this:  Please visit this EOL data page for more.......

That way users know they are staying on EOL and that is the resource they are being directed to.

Once that change is done, I'm happy with it all.  Thanks!

**Comment by jhpoelen** [comment]
@mariestuder I've applied your suggestion . . . thanks!

**Comment by mariestuder** [comment]
Wonderful!  Thanks!

**Comment by jhammock** [comment]
Oof, making these by hand is tedious! Just made two more for demo purposes, so now we have seals, sea otters and river limpets:
http://eol.org/collections/113457
http://eol.org/collections/115123
http://eol.org/collections/115122

The latter two are equipped with the title and description supplied by the test JSON output. Jorrit, I had to change two things: 

eg: <a href=\"http://globalbioticinteractions.org\"> the backslashes had to go, then the links work fine.

\n   Not recognized. <br> or <p></p> work. Frankly, once in the list I prefer just spaces between the items; I don't want to take up excessive screenspace for the various wordings.

Interestingly, Phocidae didn't make the google analytics cut, so I just left the original search string text in the description, since that collection has not been automatically generated.

Most searches I have tried work well! I failed with the fairly awkward tense, "sea otter eats"...

**Comment by jhpoelen** [comment]
@jhammock thanks for creating the collections. . . manually! Imagine this would be automated using . . . the new EOL collections API!

I've removed the newlines in the description. About the backslashes in the URLs - these are valid JSON escape characters, so any JSON parser would remove the backslashes automagically.

**Comment by jhammock** [comment]
There's no keeping up with you, Jorrit...

I was thinking as an exercise tomorrow we could show people a picture of a sea otter or seal and ask them to inquire of EOL what this animal eats, to see how many find their way. Of course, no good way to set the task (that I can think of) without priming them with some version of the wording. Marie, what do you think? Not a very authentic test group of course...

**Comment by mariestuder** [comment]
Hey Jen!  (Hi Jorrit!)

I think having people do the search is a great idea.  You do have to prime them, but I think you can ask them to come up with different phrases to query EOL around the concept of "what seals eat".  I think they will have fun with it and people will have different ways of asking that.

Fun!

And, soon.....no more manual creation of these collections!!

Best,
Marie

--------------
Marie Studer Ph.D.
Learning + Education Director
Encyclopedia of Life

Office:  617 496-1560
Mobile:  617 999-3700

**Comment by jhpoelen** [comment]
The new trait bank helps to summarize diets of popular taxa using imported GloBI indexed data. See An, S. et al., 2020. Scientific Modeling Using Large Scale Knowledge. Artificial Intelligence in Education, pp.20–24. Available at: https://doi.org/10.1007/978-3-030-52240-7_4. .
