### ISSUE TITLE
Suggestion: add mammalbase for interactions

### ISSUE THREAD

**Issue by aeiche01** [globalbioticinteractions/globalbioticinteractions#869]
From what I can see, the online MammalBase database is not present in the interaction database. It might be helpful to include this as well.

https://www.mammalbase.net/ids

**Comment by jhpoelen** [comment]
@aeiche01 thanks for sharing! Would you happen to know where mammalbase data is published?

**Comment by aeiche01** [comment]
It appears to be on the website itself (https://www.mammalbase.net/ds/). I sent an email to the curator asking if there was a master data sheet somewhere that I could use for an ongoing project, so I think you might want to contact the curator directly.

[kari.lintulaakso@helsinki.fi]

**Comment by jhpoelen** [comment]
@aeiche01 thanks for sharing the pointer to the data as published in html pages. I'd be curious to hear about the master datasheet also. I sent an email to Kari just now.

**Comment by jhpoelen** [comment]
I just heard back from Kari. and pointed out related (data) publications: 

Lintulaakso, K., Tatti, N. & Žliobaitė, I. Quantifying mammalian diets. Mamm Biol (2022). https://doi.org/10.1007/s42991-022-00323-6 

and the dataset is available at 

Lintulaakso, Kari. 2022. ”MammalBase — Dataset 02: Mammalian diets”. Version 1. Kari Lintulaakso. https://doi.org/10.23729/dba945eb-8536-4954-a6a6-be9f457c80c9

it appears that the data publication at https://doi.org/10.23729/dba945eb-8536-4954-a6a6-be9f457c80c9 (redirects to https://etsin.fairdata.fi/dataset/7b5e0808-228c-4c56-bd44-84b37b5c3edf) is designed to be downloaded manually only. This was confirmed by https://etsin.fairdata.fi/ support.

I think this a great example that shows that FAIR data isn't always open. 

Hopefully, we'll find a way to have GloBI (and other projects) index MammalBase for re-use and discovery without have to resort to manual workflows.

**Comment by jhpoelen** [comment]
fyi @aeiche01 re: MammalBase indexing by GloBI  

Over the last year, I've had an extended email exchange with @karilint (see related issue https://github.com/tdwg/interaction/issues/25#issuecomment-1202167249) of MammalBase on working with the maintainers of https://etsin.fairdata.fi/ to help make recent versions of MammalBase openly accessible so that GloBI (and others) can index these valuable dataset. A meeting is planned on May 3 2023, and I am eager to hear from @karilint what the outcomes of these discussions are.

Thanks for being patient as we are trying to figure this out.

**Comment by jhpoelen** [comment]
To help index the MammalBase, a openly accessible data endpoint is needed, so that the dataset can be accessible via some URL without having to provide credentials or performing manual operations. 

Many other species interaction datasets provide such open access endpoints. You can find many examples of those at https://globalbioticinteractions.org/datasets including:

https://github.com/hurlbertlab/dietdatabase 

https://github.com/blueraleigh/squamatabase 

iNaturalist.org 

etc.

**Comment by jhpoelen** [comment]
With tons of help from author/curator @karilint , GloBI has been able to index the diet database of MammalBase using the configuration provided using:

https://github.com/mammalbase/database 

For a first version of a GloBI data review, please see:



Also, see attached screenshots for visual evidence showing MammalBase indexed data retrieved from 

https://www.globalbioticinteractions.org/?accordingTo=globi%3Amammalbase%2Fdatabase&interactionType=ecologicallyRelatedTo

and 

https://www.globalbioticinteractions.org/browse/?accordingTo=globi%3Amammalbase%2Fdatabase&interactionType=ecologicallyRelatedTo&resultType=json

![Screenshot from 2023-08-25 08-12-13](https://github.com/globalbioticinteractions/globalbioticinteractions/assets/1084872/ae45689e-3a9f-4dd5-8e45-34486b6e04be)


![image](https://github.com/globalbioticinteractions/globalbioticinteractions/assets/1084872/01398260-5ef1-4617-8611-d65532b6e111)
