### ISSUE TITLE
encyclopedia of life page contains "Missing page" when linking to GloBI indexed species interaction records.

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/globalbioticinteractions#970]
On looking at #969 related queries, I found that page:

https://eol.org/pages/393274/data (see attached screenshot).

contains references to GloBI indexed species interaction records with "Missing page" references. 

@jhammock @KatjaSchulz Can you please let me know what I can do to replace the "Missing page" text with the related data source reference?

Thanks!

![image](https://github.com/globalbioticinteractions/globalbioticinteractions/assets/1084872/34b882ef-12dc-43f8-9bed-1b5d5dca538e)

**Comment by jhammock** [comment]
@eliagbayani can you verify if these are examples of the ghost records the reharvest process is failing to delete? When I query the graph they do not exist. If I understand the situation, that raises another question, to wit, why the most recent harvest didn't provide any new records for this source taxon and predicate, since previous harvests clearly did and they are still present at GloBI. I wonder if the presence of ghost records interferes with publication of similar records in a new harvest. 

@jhpoelen if my guess is right, there's nothing you can do, but thank you for reporting. We're working on this Failure To Delete issue and are pretty sure it's native to EOL. It may be that only GloBI is affected, but that could be because those records are a different shape from our other data.

**Comment by jhpoelen** [comment]
@jhammock thanks for your prompt reply. I'll keep the issue open for a little to keep the "ghost record" examples are verified.
