### ISSUE TITLE
neo4j down ?

### ISSUE THREAD

**Issue by weepy** [globalbioticinteractions/globalbioticinteractions#987]
Hi i was trying to get to the web admin via 

https://neo4j.globalbioticinteractions.org/webadmin/#/data/search

but it throws an error . Is it down ?

**Comment by jhpoelen** [comment]
Hi @weepy - thanks for your message. Bummer that you got an error page. 

The reason why you are unable to connect to the neo4j interface is because it is no longer publicly available. Allowing to run open-ended queries (e.g., Cypher queries) on a public neo4j causes the main GloBI website and API to be at the mercy of whoever happens to run a query.  Also, having folks write queries that run against specific versions of neo4j and/or GloBI schema would provide less room for doing software maintenance (e.g., upgrade neo4j, optimize GloBI schema). 

In other words, the neo4j instance that GloBI website / API is using is up and running, but no longer publicly accessible to run queries on it directly. This is also why rglobi > 0.3.x doesn't support running Cypher queries directly anymore (see https://github.com/ropensci/rglobi/releases/tag/v0.3.4) .

However, you run your own instance by downloading a neo4j db archive from https://globalbioticinteractions.org/data and run it with a supported neo4j version (currently an "ancient" version v3.5.x, but see also  #860 ).

Apologies for the inconvenience, and I hope you understand that GloBI is trying to balance providing easier access to millions of openly available species interaction claims with keeping the overhead/cost of running servers / maintenance down.

Also, please do share any ideas you may have to make it easier to access openly available species interaction data records.

PS I'll make a separate issue for removing any reference to neo4j access in the documentation.

**Comment by weepy** [comment]
hey thanks Jorrit - completely understand you dont have the free compute to
let anyone do whatever they fancy! I did download the data already tried to
import - but I see I probably have the wrong version (too new).

J

**Comment by jhpoelen** [comment]
Thanks for understanding. I do realize that the neo4j version is a bit ancient, and you may have to do some digging on the neo4j site to get it installed.

Here's the instructions that I used to install it on the GloBI infrastructure - 

https://github.com/globalbioticinteractions/globi-server-scripts/blob/dc2130862b82456d04ed2fdc8cdb9a4cc5e01e59/install.md#install-neo4j

There's an open issue on upgrading neo4j #860 . . . so, if you feel motivated . . .  ; )

-jorrit

**Comment by jhpoelen** [comment]
@weepy I made an attempt to update documentation at https://globalbioticinteractions.org/data and https://github.com/globalbioticinteractions/globalbioticinteractions/wiki/Cypher . Also, https://neo4.globalbioticinteractions.org now redirects to https://globalbioticinteractions.org/data . 

Please feel free to re-open this issue or add comments if you feel the issue has not been addressed. 

Thanks for being patient, and curious to hear how you'll end up using species interaction data in your project.
